### ISSUE TITLE
[TYPO] "Check free DLC no onwed"

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-checkdlc-plugin#16]
In Playnite > Extensions > CheckDlc. I'm thinking it should be "Check free DLC not owned."

Thanks for your work, and merry Christmas/whatever holiday you celebrate. :)

**Comment by shakeyourbunny** [comment]
Did just a test with the version (0.3x): 
- got free DLCs only for Epic (and one, the Ark Islands DLC with the Ark DLC I already have taken).
- Neon Abyss showed me a free DLC on Steam
- hit "refresh data": the above entry vanished.

Update to 0.4.1:
- same situation as above.
- hit "refresh data"
- the Ark Islands free DLC with the ARK editor vanished
- only Epic DLCs are seen.

I don't know why CheckDLC only considers DLCs from Epic Store and ignores any other library.

some log snippets:
```` 
04-01 20:38:39.741|ERROR|CheckDlc#Common:Error on GetFromSteamWebApi()|D:\GitHub\Lacro59\playnite-checkdlc-plugin\source\Clients\SteamDlc.cs|173
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 265
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 310
   at CheckDlc.Clients.SteamDlc.GetFromSteamWebApi(String AppId) in D:\GitHub\Lacro59\playnite-checkdlc-plugin\source\Clients\SteamDlc.cs:line 173
````
````
04-01 20:58:51.753|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(ARK Editor - d28bd15e-bdbc-422b-a77c-411ff268e27a)
04-01 20:58:51.753|INFO |CheckDlc#GenericDlc:Get Dlc for ARK Editor with Epic
04-01 20:58:56.560|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(Pathfinder: Kingmaker - ad09ae73-1b8b-46f7-9767-45de294d7f2b)
04-01 20:58:56.560|INFO |CheckDlc#GenericDlc:Get Dlc for Pathfinder: Kingmaker with Epic
04-01 20:58:58.964|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(Pathfinder: Kingmaker - ad09ae73-1b8b-46f7-9767-45de294d7f2b)
04-01 20:58:58.964|INFO |CheckDlc#GenericDlc:Get Dlc for Pathfinder: Kingmaker with Epic
04-01 20:59:01.321|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(Neon Abyss - ac44e2ba-fb5a-4b02-a274-6acb94f278eb)
04-01 20:59:01.321|INFO |CheckDlc#GenericDlc:Get Dlc for Neon Abyss with Steam
04-01 20:59:03.673|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(A Total War Saga: Troy - 7f699497-8089-4691-a675-ec69f59b0523)
04-01 20:59:03.673|INFO |CheckDlc#GenericDlc:Get Dlc for A Total War Saga: Troy with Epic
04-01 20:59:06.562|INFO |CheckDlc#PluginDatabaseObject`3:Task Refresh() - 00:14.80 for 5/5 items
...
04-01 21:01:39.810|INFO |CheckDlc#PluginDatabaseObject`3:LoadDatabase with 12885 items - 00:08.85
...
04-01 21:02:15.728|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(Pathfinder: Kingmaker - ad09ae73-1b8b-46f7-9767-45de294d7f2b)
04-01 21:02:15.728|INFO |CheckDlc#GenericDlc:Get Dlc for Pathfinder: Kingmaker with Epic
04-01 21:02:18.794|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(Pathfinder: Kingmaker - ad09ae73-1b8b-46f7-9767-45de294d7f2b)
04-01 21:02:18.794|INFO |CheckDlc#GenericDlc:Get Dlc for Pathfinder: Kingmaker with Epic
04-01 21:02:23.628|INFO |CheckDlc#PluginDatabaseObject`3:RefreshNoLoader(A Total War Saga: Troy - 7f699497-8089-4691-a675-ec69f59b0523)
04-01 21:02:23.628|INFO |CheckDlc#GenericDlc:Get Dlc for A Total War Saga: Troy with Epic
04-01 21:02:28.434|INFO |CheckDlc#PluginDatabaseObject`3:Task Refresh() - 00:12.71 for 3/3 items
````

**Comment by chocolatechipcats** [comment]
@shakeyourbunny I think your issue is separate and ought to be its own bug?

**Comment by shakeyourbunny** [comment]
@chocolatechipcats I am not aware of a related bug for this plugin.

I'm a bit puzzled why the Steam DLC scan was fixed, but does only consider Epic DLCs for on looking for unowned free DLCs.

**Comment by chocolatechipcats** [comment]
You can make a new issue by clicking the 'new issue' button. Mine was only reporting a typo in the menu.

**Comment by shakeyourbunny** [comment]
@chocolatechipcats I apologize, I have moved it to my own issue.

**Comment by chocolatechipcats** [comment]
No problem :)
