### ISSUE TITLE
Error converting value {null}

### ISSUE THREAD

**Issue by oryband** [Lacro59/playnite-checkdlc-plugin#57]
I repeatedly get an error downloading all plugin data at once. Here's the most relevant section, also see attached logs:

```csharp
30-12 22:33:31.772|ERROR|Serialization:Failed to deserialize CommonPluginsStores.Epic.Models.EpicAddonsByNamespace from json:
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path 'data.Catalog.catalogOffers.elements[1].releaseDate', line 1, position 7950. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

- [playnite.log](https://github.com/Lacro59/playnite-checkdlc-plugin/files/10330617/playnite.log)
- [extensions.log](https://github.com/Lacro59/playnite-checkdlc-plugin/files/10330616/extensions.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/ef089c4094114cd67548ff7b22d0bc5b889c0d6d
