### ISSUE TITLE
Causes Playnite to crash from a 'cold' start

### ISSUE THREAD

**Issue by BloodShed-Oni** [Lacro59/playnite-checkdlc-plugin#77]
When starting Playnite (on Windows startup or after closing Playnite completely) CheckDLC will often cause an unreacoverable error,

![image](https://github.com/user-attachments/assets/618de561-f611-4696-bae0-6147bfda9c7a)

Choosing to restart Playnite will make it start normally.

The crash can happen during normal use, but it's rare and doesn't follow the same pattern every time.
Starting playnite after it's been shutdown completely is the most consistent method to make CheckDLC cause a crash.

 

 
Here's what I found in the playnite.log
```
14-07 00:07:28.034|INFO |PlayniteApplication:Application 10.33.0.16167 started
14-07 00:07:29.052|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommonPluginsShared.Collections.PluginDatabaseObject`4.Games_ItemUpdated(Object sender, ItemUpdatedEventArgs`1 e) in D:\GitHub\Lacro59\playnite-checkdlc-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:line 998
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Playnite.Database.ItemCollection`1.OnItemUpdated(IEnumerable`1 updates) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 623
   at Playnite.Database.ItemCollection`1.Update(IEnumerable`1 itemsToUpdate) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 568
   at Playnite.Database.GamesCollection.Update(IEnumerable`1 itemsToUpdate) in C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:line 200
   at DuplicateHider.DuplicateHiderPlugin.<OnApplicationStarted>d__49.MoveNext() in E:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71
14-07 00:07:31.184|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: 98b4fb85-ff19-44f0-8f37-60a32f0f5019
```

**Comment by BloodShed-Oni** [comment]
> Can you try with the last version?

Just tested it out with with a handful of cold starts with Playnite, and no crash or error's.
